version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm install"
      - run: yarn
      - run: CI=true yarn run build  
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Testing stufff"
      - run: yarn
      - run: yarn test
  hithere:
    docher:
      -image: curcleci/node:8.9

    steps:
      - checkout
      - run: echo "Hello"
workflows:
    version: 2
    build_test_and_lint:
      jobs:
        - build
        - hithere
        - test:
            requires:
              - hithere
            
  